site_name: RingCentral Developer Quickstart
site_url: https://developers.ringcentral.com
repo_url: https://github.com/grokify/ringcentral-docs-quickstart
docs_dir: docs
theme: readthedocs
pages:

- ['index.md', 'Quickstart', 'Overview']
- ['answering_rules.md', 'Quickstart', 'Answering Rules']
- ['call_queue.md', 'Quickstart', 'Call Queue']
- ['webhooks.md', 'Quickstart', 'Webhooks']
